# Generated by Django 4.2.3 on 2023-07-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='CategoryApp.category'),
        ),
    ]
